# GoReleaser Configuration for Cortex-Embed
# This config is used exclusively for cortex-embed releases (embed-v* tags)
# https://goreleaser.com

version: 2

# Override project name to get simpler filenames (cortex-embed vs project-cortex-embed)
project_name: cortex

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  # ============================================================================
  # cortex-embed (with Python runtime, platform-specific builds)
  # ============================================================================
  # Note: Python dependencies must be pre-generated for each platform
  # The GitHub Actions workflow handles this before running goreleaser

  - id: cortex-embed-darwin-amd64
    main: ./cmd/cortex-embed
    binary: cortex-embed

    ldflags:
      - -s -w
      - -X 'project-cortex/internal/cli.Version={{.Version}}'
      - -X 'project-cortex/internal/cli.GitCommit={{.ShortCommit}}'
      - -X 'project-cortex/internal/cli.BuildDate={{.Date}}'

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
    goarch:
      - amd64

  - id: cortex-embed-darwin-arm64
    main: ./cmd/cortex-embed
    binary: cortex-embed

    ldflags:
      - -s -w
      - -X 'project-cortex/internal/cli.Version={{.Version}}'
      - -X 'project-cortex/internal/cli.GitCommit={{.ShortCommit}}'
      - -X 'project-cortex/internal/cli.BuildDate={{.Date}}'

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
    goarch:
      - arm64

  - id: cortex-embed-linux-amd64
    main: ./cmd/cortex-embed
    binary: cortex-embed

    ldflags:
      - -s -w
      - -X 'project-cortex/internal/cli.Version={{.Version}}'
      - -X 'project-cortex/internal/cli.GitCommit={{.ShortCommit}}'
      - -X 'project-cortex/internal/cli.BuildDate={{.Date}}'

    env:
      - CGO_ENABLED=0

    goos:
      - linux
    goarch:
      - amd64

  - id: cortex-embed-linux-arm64
    main: ./cmd/cortex-embed
    binary: cortex-embed

    ldflags:
      - -s -w
      - -X 'project-cortex/internal/cli.Version={{.Version}}'
      - -X 'project-cortex/internal/cli.GitCommit={{.ShortCommit}}'
      - -X 'project-cortex/internal/cli.BuildDate={{.Date}}'

    env:
      - CGO_ENABLED=0

    goos:
      - linux
    goarch:
      - arm64

  - id: cortex-embed-windows-amd64
    main: ./cmd/cortex-embed
    binary: cortex-embed

    ldflags:
      - -s -w
      - -X 'project-cortex/internal/cli.Version={{.Version}}'
      - -X 'project-cortex/internal/cli.GitCommit={{.ShortCommit}}'
      - -X 'project-cortex/internal/cli.BuildDate={{.Date}}'

    env:
      - CGO_ENABLED=0

    goos:
      - windows
    goarch:
      - amd64

archives:
  - id: cortex-embed
    ids:
      - cortex-embed-darwin-amd64
      - cortex-embed-darwin-arm64
      - cortex-embed-linux-amd64
      - cortex-embed-linux-arm64
      - cortex-embed-windows-amd64
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-embed_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: mvp-joe
    name: project-cortex

  # Release notes template
  header: |
    ## Cortex-Embed {{ .Tag }}

    ### Installation

    **cortex-embed (with Python runtime, ~150MB download / 300MB extracted)**
    ```bash
    # Download platform-specific binary from assets below:
    # macOS (ARM): cortex-embed_{{ .Version }}_darwin_arm64.tar.gz (~150MB)
    # macOS (Intel): cortex-embed_{{ .Version }}_darwin_x86_64.tar.gz (~150MB)
    # Linux (x64): cortex-embed_{{ .Version }}_linux_x86_64.tar.gz (~150MB)
    # Linux (ARM): cortex-embed_{{ .Version }}_linux_arm64.tar.gz (~150MB)
    # Windows: cortex-embed_{{ .Version }}_windows_x86_64.zip (~150MB)
    ```

    ### What's Changed

  footer: |
    ---

    **Full Changelog**: https://github.com/mvp-joe/project-cortex/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Notes
    - This release contains only the `cortex-embed` embedding server
    - Includes embedded Python runtime and all dependencies (~300MB extracted)
    - For the main `cortex` CLI, see the latest `v*` release
    - Most users only need cortex-embed if they want local embedding generation

  # Disable auto-release draft
  draft: false

  # Don't mark as prerelease (embed suffix is for workflow routing, not prerelease status)
  prerelease: false

  # Changelog mode
  mode: append

  # Don't compete with cortex releases for "latest" - embed has independent versioning
  make_latest: false
