# GoReleaser Configuration for Project Cortex
# https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  # ============================================================================
  # cortex CLI (lightweight, all platforms)
  # ============================================================================
  - id: cortex
    main: ./cmd/cortex
    binary: cortex

    ldflags:
      - -s -w
      - -X 'project-cortex/internal/cli.Version={{.Version}}'
      - -X 'project-cortex/internal/cli.GitCommit={{.ShortCommit}}'
      - -X 'project-cortex/internal/cli.BuildDate={{.Date}}'

    env:
      - CGO_ENABLED=1

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # macOS-specific settings
    goamd64:
      - v1

    # Ignore unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: cortex
    builds:
      - cortex
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: mvp-joe
    name: project-cortex

  # Release notes template
  header: |
    ## Cortex CLI {{ .Tag }}

    ### Installation

    **cortex CLI (lightweight, ~7MB)**
    ```bash
    # macOS/Linux via go install
    go install github.com/mvp-joe/project-cortex/cmd/cortex@{{ .Tag }}

    # Or download pre-built binary:
    # macOS (ARM): cortex_{{ .Version }}_darwin_arm64.tar.gz
    # macOS (Intel): cortex_{{ .Version }}_darwin_x86_64.tar.gz
    # Linux: cortex_{{ .Version }}_linux_x86_64.tar.gz
    # Windows: cortex_{{ .Version }}_windows_x86_64.zip
    ```

    ### What's Changed

  footer: |
    ---

    **Full Changelog**: https://github.com/mvp-joe/project-cortex/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Notes
    - This release contains only the `cortex` CLI binary
    - For the embedding server, see the latest `embed-v*` release

  # Disable auto-release draft
  draft: false

  # Mark pre-releases
  prerelease: auto

  # Changelog mode
  mode: append

  # Make release immediately available
  make_latest: true

# Homebrew tap (optional - for future)
# brews:
#   - name: cortex
#     ids:
#       - cortex
#     repository:
#       owner: mvp-joe
#       name: homebrew-tap
#     homepage: https://github.com/mvp-joe/project-cortex
#     description: Make your AI coding assistant literally smarter
#     license: Apache-2.0

# Docker images (optional - for future)
# dockers:
#   - image_templates:
#       - "ghcr.io/mvp-joe/cortex:{{ .Tag }}"
#       - "ghcr.io/mvp-joe/cortex:latest"
