# Cortex Configuration Example
# Copy this file to .cortex/config.yml and customize for your project

# Embedding provider configuration
embedding:
  provider: "local"  # Options: "local", "openai"
  model: "BAAI/bge-small-en-v1.5"
  dimensions: 384
  endpoint: "http://localhost:8121/embed"

# File paths configuration
paths:
  # Glob patterns for code files to index
  code:
    - "**/*.go"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.py"
    - "**/*.rs"
    - "**/*.c"
    - "**/*.cpp"
    - "**/*.cc"
    - "**/*.h"
    - "**/*.hpp"
    - "**/*.php"
    - "**/*.rb"
    - "**/*.java"

  # Glob patterns for documentation files to index
  docs:
    - "**/*.md"
    - "**/*.rst"

  # Glob patterns to ignore
  ignore:
    - "node_modules/**"
    - "vendor/**"
    - ".git/**"
    - "dist/**"
    - "build/**"
    - "target/**"
    - "__pycache__/**"
    - "*.test"
    - "*.pyc"

# Chunking strategy configuration
chunking:
  # Code extraction strategies (symbols, definitions, data - not chunked, extracted as complete units)
  strategies: ["symbols", "definitions", "data"]

  # Documentation chunking (split by headers/sections)
  doc_chunk_size: 400      # Max tokens per documentation chunk (safe for 384-dim embeddings)
  doc_overlap: 50          # Token overlap between doc chunks

# Environment Variable Overrides:
# You can override any configuration value using environment variables with the CORTEX_ prefix.
# Examples:wh
#   CORTEX_EMBEDDING_PROVIDER=openai
#   CORTEX_EMBEDDING_ENDPOINT=https://api.openai.com/v1/embeddings
#   CORTEX_CHUNKING_DOC_CHUNK_SIZE=1000
