name: Release Cortex CLI

on:
  push:
    tags:
      - 'v*'
      - '!v*-embed'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    name: Release Cortex CLI with GoReleaser
    runs-on: ubuntu-latest
    # Only run if tag does NOT end with -embed
    if: "!endsWith(github.ref, '-embed')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cortex-release-artifacts
          path: dist/
          retention-days: 7
