name: Release

on:
  push:
    tags:
      - 'v*'
      - '!v*-embed'

permissions:
  contents: write
  packages: write

jobs:
  # ============================================================================
  # Generate Python dependencies for all platforms
  # ============================================================================
  generate-python-deps:
    name: Generate Python Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Generate Python dependencies for all platforms
        run: |
          echo "Generating Python dependencies for all platforms..."
          cd internal/embed/server
          go run ./generate -platforms=darwin-amd64,darwin-arm64,linux-amd64,linux-arm64,windows-amd64
        timeout-minutes: 30

      - name: Upload Python dependencies artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-deps
          path: internal/embed/server/data/
          retention-days: 1

  # ============================================================================
  # Build and release binaries
  # ============================================================================
  goreleaser:
    name: Release with GoReleaser
    needs: generate-python-deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Download Python dependencies
        uses: actions/download-artifact@v4
        with:
          name: python-deps
          path: internal/embed/server/data/

      - name: Verify Python dependencies
        run: |
          echo "Checking Python dependencies..."
          ls -lh internal/embed/server/data/
          for platform in darwin-amd64 darwin-arm64 linux-amd64 linux-arm64 windows-amd64; do
            if [ -d "internal/embed/server/data/$platform" ]; then
              size=$(du -sh "internal/embed/server/data/$platform" | cut -f1)
              echo "✓ $platform ($size)"
            else
              echo "✗ $platform missing!"
              exit 1
            fi
          done

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: dist/
          retention-days: 7
